//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legend_Špedicija.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_SMTP_parameter
    {
        public int Id { get; set; }
        public string UserEmail { get; set; }
        public string password { get; set; }
        public string host { get; set; }
        public int RowCreatedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowCreatedDateTime { get; set; }
        public int RowModifiedSYSUserID { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
    }
}
