//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legend_Špedicija.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_Preference
    {
        public int PreferencesId { get; set; }
        public int SYSUserID { get; set; }
        public Nullable<int> NoOfUsersDisplayed { get; set; }
    
        public virtual SYSUser SYSUser { get; set; }
    }
}
