ALTER TABLE [dbo].[SYSUserProfile] WITH CHECK ADD FOREIGN KEY([SYSUserID])
REFERENCES [dbo].[SYSUser] ([SYSUserID]);

ALTER TABLE [dbo].[SYSUserRole] WITH CHECK ADD FOREIGN KEY([LOOKUPRoleID])
REFERENCES [dbo].[LOOKUPRole] ([LOOKUPRoleID]);

ALTER TABLE [dbo].[SYSUserRole] WITH CHECK ADD FOREIGN KEY([SYSUserID])
REFERENCES [dbo].[SYSUser] ([SYSUserID]);

ALTER TABLE [dbo].[USER Preferences] WITH CHECK
	ADD FOREIGN KEY ([SYSUserID]) REFERENCES [dbo].[SYSUser] ([SYSUserID]);


ALTER TABLE [dbo].[Message]
	ADD CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED ([MessageID] ASC)
	WITH (
		PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON
	);